export const PathRoutes = {
  home: "/",
  products: "/products",
  productsDetail: "/products/:productId",
  introduce: "/introduce",
  news: "/news",
  newsDetail: "/news/:newId",
  search: "/search",
  searchName: "/search/:searchName/:searchPage",
  contact: "/contact",
  carts: "/carts",
  profile: "/profile",
  editProfile: "/editprofile",
  register: "/register",
  login: "/login",
  pay: "/pay",
  createItem: "/createItem",
  editItem: "/editItem",
  editItemId: "/editItem/:idItem",
  adminGetOrders: "/adminGetOrders",
  notFound: "*",
};
